package com.tecin.mina.model;

public enum TipoExamen {
    EXAMEN_MEDICO_GENERAL,
    EXAMEN_AUDIOMETRICO,
    EXAMEN_OCUPACIONAL,
    EXAMEN_PSICOLOGICO,
    EXAMEN_TOXICOLOGICO,
    EXAMEN_ESPIRACION,
    EXAMEN_RADIOLOGICO
}
